title: Annie(Ai-Yun) Wu
logo: "images/biopic.jpeg"
description: >
  Speak with Data
  <br><br>
  <a href="https://www.linkedin.com/in/aiyunwu/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
